apiVersion: v1
kind: Service
metadata:
  name: homefinance
spec:
  selector:
    app: homefinance
  ports:
    - name: app-port
      port: 8585
      targetPort: 8585
    - name: debug-port
      port: 5005
      targetPort: 5005
  type: NodePort