apiVersion: apps/v1
kind: Deployment
metadata:
  name: homefinance-deployment
  labels:
    app: homefinance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homefinance
  template:
    metadata:
      labels:
        app: homefinance
    spec:
      containers:
      - name: homefinance-container
        image: 0x4147/homefinance:1.0 
        ports:
        - containerPort: 8586
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: homefinance-service
spec:
  selector:
    app: homefinance
  ports:
    - protocol: TCP
      port: 8586
      targetPort: 8586
      nodePort: 30001
  type: LoadBalancer  
