-- Person
INSERT INTO person (code, name, email)
VALUES
    ('ASANKA', 'Asanka', 'asanka.nz@gmail.com'),
    ('DIVYA', 'Divya', 'divyamehta.nz@gmail.com');

-- Category
INSERT INTO category (name, type)
VALUES
    ('Utility Bill', 'EXPENSE'),
    ('Groceries', 'EXPENSE'),
    ('Transportation', 'EXPENSE'),
    ('Healthcare', 'EXPENSE'),
    ('Entertainment', 'EXPENSE'),
    ('Mortgage', 'EXPENSE'),
    ('Property tax', 'EXPENSE'),
    ('Insurance', 'EXPENSE'),
    ('Car repair', 'EXPENSE'),
    ('Home maintenance', 'EXPENSE'),
    ('Salary', 'INCOME'),
    ('Rental Income', 'INCOME'),
    ('Government Grants', 'INCOME'),
    ('Take Out', 'EXPENSE'),
    ('Amazon', 'EXPENSE'),
    ('Temu', 'EXPENSE'),
    ('Card payment', 'INCOME'),
    ('Card loan', 'EXPENSE'),
    ('Alcohol', 'EXPENSE'),
    ('Clothing', 'EXPENSE'),
    ('Shopping', 'EXPENSE'),
    ('Travel', 'EXPENSE'),
    ('Bank Fees', 'EXPENSE');


-- PersonCard
INSERT INTO person_card (person_id, card_identifier)
SELECT person_id, '5223********5844' FROM person WHERE code = 'ASANKA';
INSERT INTO person_card (person_id, card_identifier)
SELECT person_id, '5223********3406' FROM person WHERE code = 'DIVYA';


-- merchant_rule
-- Rules are matched against a normalized key (city, store numbers, punctuation and apostrophes removed),
-- so a rule is plain brand words: no digits, no trailing city. Longer / more specific rules win.
INSERT INTO merchant_rule (normalized_merchant, category_id, source)
VALUES
    ('costco', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('fortinos', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('supermarket', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('freshco', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('wal mart', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('grocery', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('food basics', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('sobeys', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('swadesh', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('walmart', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('desi mandi', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('no frills', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('nofrills', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('farm boy', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('desi mart', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('chris jenn', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('loblaws', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('zehrs', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('bulk barn', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('longos', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('metro', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('fresh manna', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('adonis', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('meats', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('kardamom kitchen', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('shawarma', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('spring sushi', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('tim hortons', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('popeyes', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('mcdonalds', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('mcdonald', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('originalshawarma', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('cafe', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('restaurant', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('castelli', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('chick fil a', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('burger king', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('crepe delicious', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('szechuan express', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('thai express', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('scaddabush', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('starbucks', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('subway', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('pizza', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('burrito', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('freshii', (SELECT category_id FROM category WHERE name = 'Groceries'), 'SEED'),
    ('demetres', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('chipotle', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('wild fork', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('mary browns', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('momo', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('parikar', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('rajdhani', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('royal paan', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('chat hut', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('apna pind', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('peller', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('sweet paradise', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('onroute', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('wendys', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('kfc', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('harveys', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('dairy queen', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('dominos', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('panera', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('nandos', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('booster juice', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('dunkin', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('krispy kreme', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('mr sub', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('sushi', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('kitchen', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('grill', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('bistro', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('bakery', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('sweets', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('indian', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('nepali', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('tandoori', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('biryani', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('noodle', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('wings', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('bbq', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('diner', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('steakhouse', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('tacos', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('thai', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('ramen', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('uber eats', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('doordash', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('skipthedishes', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('pho', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('pita', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('kebab', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('donair', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('chinese', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('pub', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('caffe', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('gelato', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('gelateria', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('catering', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('take out', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('wok box', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('winery', (SELECT category_id FROM category WHERE name = 'Take Out'), 'SEED'),
    ('midas', (SELECT category_id FROM category WHERE name = 'Car repair'), 'SEED'),
    ('carfax', (SELECT category_id FROM category WHERE name = 'Car repair'), 'SEED'),
    ('ford lincoln', (SELECT category_id FROM category WHERE name = 'Car repair'), 'SEED'),
    ('parking', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('honk', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('esso', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('pioneer', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('uber', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('spothero', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('parkedin', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('petro canada', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('shell', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('husky', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('go transit', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('presto', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('ultramar', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('toll', (SELECT category_id FROM category WHERE name = 'Transportation'), 'SEED'),
    ('peoples pharmachoice', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('shoppers drug mart', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('st joseph', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('mcmaster', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('healthcare', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('rexall', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('dental', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('dentist', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('drshambly', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('dent prof', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('physio', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('optical', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('pharmacy', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('sport med', (SELECT category_id FROM category WHERE name = 'Healthcare'), 'SEED'),
    ('amazon', (SELECT category_id FROM category WHERE name = 'Amazon'), 'SEED'),
    ('amzn', (SELECT category_id FROM category WHERE name = 'Amazon'), 'SEED'),
    ('temu', (SELECT category_id FROM category WHERE name = 'Temu'), 'SEED'),
    ('the home depot', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('ikea', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('canadian tire', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('best buy', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('dollarama', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('reliance', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('sherwin williams', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('rona', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('home hardware', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('lowes', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('cdn tire', (SELECT category_id FROM category WHERE name = 'Home maintenance'), 'SEED'),
    ('lcbo', (SELECT category_id FROM category WHERE name = 'Alcohol'), 'SEED'),
    ('the beer store', (SELECT category_id FROM category WHERE name = 'Alcohol'), 'SEED'),
    ('payment', (SELECT category_id FROM category WHERE name = 'Card payment'), 'SEED'),
    ('thank you', (SELECT category_id FROM category WHERE name = 'Card payment'), 'SEED'),
    ('wfcuconditional', (SELECT category_id FROM category WHERE name = 'Card loan'), 'SEED'),
    ('alectra', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('enbridge', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('bell canada', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('bell mobility', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('koodo', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('rogers', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('telus', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('fido', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('virgin plus', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('freedom mobile', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('hamilton utility', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('hydro', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('teksavvy', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('distributel', (SELECT category_id FROM category WHERE name = 'Utility Bill'), 'SEED'),
    ('old navy', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('h m', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('carters', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('marshalls', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('sport chek', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('roots', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('shein', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('foot locker', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('winners', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('zara', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('uniqlo', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('nike', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('adidas', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('childrens place', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('gap', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('kid to kid', (SELECT category_id FROM category WHERE name = 'Clothing'), 'SEED'),
    ('security national', (SELECT category_id FROM category WHERE name = 'Insurance'), 'SEED'),
    ('insurance', (SELECT category_id FROM category WHERE name = 'Insurance'), 'SEED'),
    ('intact', (SELECT category_id FROM category WHERE name = 'Insurance'), 'SEED'),
    ('belair', (SELECT category_id FROM category WHERE name = 'Insurance'), 'SEED'),
    ('state farm', (SELECT category_id FROM category WHERE name = 'Insurance'), 'SEED'),
    ('netflix', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('spotify', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('disney plus', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('cineplex', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('youtube', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('prime video', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('crave', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('apple music', (SELECT category_id FROM category WHERE name = 'Entertainment'), 'SEED'),
    ('membership fee', (SELECT category_id FROM category WHERE name = 'Bank Fees'), 'SEED'),
    ('annual fee', (SELECT category_id FROM category WHERE name = 'Bank Fees'), 'SEED'),
    ('interest charge', (SELECT category_id FROM category WHERE name = 'Bank Fees'), 'SEED'),
    ('purchase interest', (SELECT category_id FROM category WHERE name = 'Bank Fees'), 'SEED'),
    ('staples', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('indigo', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('party city', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('petsmart', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('michaels', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('dollar tree', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('toys r us', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('lego', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('ups store', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('newegg', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('canada computers', (SELECT category_id FROM category WHERE name = 'Shopping'), 'SEED'),
    ('airbnb', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('hotels', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('amex travel', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('expedia', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('booking', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('air canada', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('westjet', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('porter airlines', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('marriott', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED'),
    ('hilton', (SELECT category_id FROM category WHERE name = 'Travel'), 'SEED');
