import React, { useState, useEffect } from 'react';
import { LayoutDashboard, PlusSquare, List, BarChart2, Calendar, Receipt, Brain } from 'lucide-react';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, PointElement, LineElement, Title } from 'chart.js';
import { Pie, Line } from 'react-chartjs-2';

// Register Chart.js components
ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, PointElement, LineElement, Title);

// --- Type Definitions for TypeScript ---
// This defines the possible views our application can have.
type View =
  | 'Dashboard'
  | 'AddBulkTransactions'
  | 'ViewTransactions'
  | 'SpendingInsights'
  | 'MonthlyBalanceChecker'
  | 'AddReceipt';

// --- Welcome Header Component ---
const WelcomeHeader = () => {
    const [currentTime, setCurrentTime] = useState(new Date());

    useEffect(() => {
        const timer = setInterval(() => {
            setCurrentTime(new Date());
        }, 1000);

        return () => clearInterval(timer);
    }, []);

    const getGreeting = () => {
        const hour = currentTime.getHours();
        if (hour < 12) return 'Good Morning';
        if (hour < 17) return 'Good Afternoon';
        return 'Good Evening';
    };

    const formatDate = (date: Date) => {
        return date.toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    };

    const formatTime = (date: Date) => {
        return date.toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        });
    };

    return (
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-8 rounded-xl shadow-lg mb-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-4xl font-bold mb-2">{getGreeting()}!</h1>
                    <p className="text-xl opacity-90">Welcome to your Home Finance Dashboard</p>
                </div>
                <div className="text-right">
                    <p className="text-2xl font-semibold">{formatDate(currentTime)}</p>
                    <p className="text-xl opacity-90">{formatTime(currentTime)}</p>
                </div>
            </div>
        </div>
    );
};

// --- Athena Summary Component ---
const AthenaSummary = () => {
    return (
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm mb-8">
            <div className="flex items-center mb-4">
                <Brain className="w-6 h-6 text-purple-600 mr-3" />
                <h2 className="text-2xl font-bold text-gray-900">Athena's Insights</h2>
            </div>
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg p-6">
                <p className="text-gray-700 text-lg leading-relaxed">
                    <span className="font-semibold text-purple-700">Athena Analysis:</span> Based on your recent transactions, 
                    I've noticed some interesting patterns in your spending habits. Your grocery expenses have increased by 15% 
                    compared to last month, while entertainment spending has decreased. You're doing well with your budget 
                    allocation for utilities and transportation. Consider reviewing your dining out expenses as they're 
                    trending upward.
                </p>
                <div className="mt-4 text-sm text-gray-600">
                    <p>• Analysis based on transactions from the past 30 days</p>
                    <p>• Generated by local AI assistant Athena</p>
                </div>
            </div>
        </div>
    );
};

// --- Pie Chart Component ---
const PieChartCard = ({ title, data, colors }: { title: string; data: any; colors: string[] }) => {
    const chartData = {
        labels: data.labels,
        datasets: [
            {
                data: data.values,
                backgroundColor: colors,
                borderColor: colors.map(color => color + '80'),
                borderWidth: 2,
            },
        ],
    };

    const options = {
        responsive: true,
        plugins: {
            legend: {
                position: 'bottom' as const,
                labels: {
                    padding: 20,
                    usePointStyle: true,
                },
            },
            tooltip: {
                callbacks: {
                    label: function(context: any) {
                        const label = context.label || '';
                        const value = context.parsed;
                        const total = context.dataset.data.reduce((a: number, b: number) => a + b, 0);
                        const percentage = ((value / total) * 100).toFixed(1);
                        return `${label}: $${value.toLocaleString()} (${percentage}%)`;
                    }
                }
            }
        },
    };

    return (
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">{title}</h3>
            <div className="h-64">
                <Pie data={chartData} options={options} />
            </div>
        </div>
    );
};

// --- Dashboard Component ---
const Dashboard = () => {
    // Placeholder data for the pie charts
    const categoryData = {
        labels: ['Groceries', 'Entertainment', 'Transportation', 'Utilities', 'Dining', 'Shopping'],
        values: [1200, 800, 600, 400, 350, 300]
    };

    const merchantData = {
        labels: ['Walmart', 'Netflix', 'Shell', 'Hydro One', 'Restaurant A', 'Amazon'],
        values: [800, 15, 200, 150, 300, 250]
    };

    const monthlyData = {
        labels: ['January', 'February', 'March'],
        values: [2800, 3200, 2650]
    };

    const colors = [
        '#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#06B6D4',
        '#84CC16', '#F97316', '#EC4899', '#6366F1', '#14B8A6', '#F43F5E'
    ];

    return (
        <div className="max-w-7xl mx-auto animate-fade-in">
            <WelcomeHeader />
            <AthenaSummary />
            
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <PieChartCard 
                    title="Spending by Category (Past 3 Months)" 
                    data={categoryData} 
                    colors={colors.slice(0, 6)} 
                />
                <PieChartCard 
                    title="Spending by Merchant (Past 3 Months)" 
                    data={merchantData} 
                    colors={colors.slice(6, 12)} 
                />
                <PieChartCard 
                    title="Spending by Month (Past 3 Months)" 
                    data={monthlyData} 
                    colors={colors.slice(0, 3)} 
                />
            </div>
        </div>
    );
};

const AddBulkTransactions = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">Add Bulk Transactions</h2>
        <p className="mt-2 text-gray-600">Upload a CSV or manually enter multiple transactions at once.</p>
    </div>
);

const ViewTransactions = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">View Transactions</h2>
        <p className="mt-2 text-gray-600">Browse, search, and filter your transaction history.</p>
    </div>
);

const SpendingInsights = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">Spending Insights</h2>
        <p className="mt-2 text-gray-600">Visualize your spending habits with charts and graphs.</p>
    </div>
);

const MonthlyBalanceChecker = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">Monthly Balance Checker</h2>
        <p className="mt-2 text-gray-600">Compare your income and expenses month over month.</p>
    </div>
);

const AddReceipt = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">Add Receipt</h2>
        <p className="mt-2 text-gray-600">Upload a receipt to automatically create a transaction.</p>
    </div>
);

// --- Sidebar Navigation Component ---
interface SidebarProps {
    activeView: View;
    setActiveView: (view: View) => void;
}

const Sidebar: React.FC<SidebarProps> = ({ activeView, setActiveView }) => {
    const menuItems: { id: number; name: View; icon: React.ElementType }[] = [
        { id: 1, name: 'Dashboard', icon: LayoutDashboard },
        { id: 2, name: 'AddBulkTransactions', icon: PlusSquare },
        { id: 3, name: 'ViewTransactions', icon: List },
        { id: 4, name: 'SpendingInsights', icon: BarChart2 },
        { id: 5, name: 'MonthlyBalanceChecker', icon: Calendar },
        { id: 6, name: 'AddReceipt', icon: Receipt },
    ];

    // Function to format the view name for display
    const formatViewName = (name: View) => name.replace(/([A-Z])/g, ' $1').trim();

    return (
        <aside className="w-64 flex-shrink-0 bg-gray-100/95 border-r border-gray-200 flex flex-col transition-all duration-300">
            <div className="h-16 flex items-center px-6 border-b border-gray-200">
                <h1 className="text-xl font-bold text-gray-900">Home Finance</h1>
            </div>
            <nav className="flex-1 px-4 py-4 space-y-1">
                {menuItems.map((item) => {
                    const isActive = activeView === item.name;
                    return (
                        <a
                            key={item.id}
                            href="#"
                            onClick={(e) => {
                                e.preventDefault();
                                setActiveView(item.name);
                            }}
                            className={`flex items-center px-4 py-2.5 text-sm font-medium rounded-lg transition-colors duration-200 ${
                                isActive
                                    ? 'bg-gray-200 text-gray-900 font-semibold'
                                    : 'text-gray-600 hover:bg-gray-200/70 hover:text-gray-800'
                            }`}
                        >
                            <item.icon className="w-5 h-5 mr-3" />
                            {formatViewName(item.name)}
                        </a>
                    );
                })}
            </nav>
        </aside>
    );
};


// --- Main App Component ---
const App: React.FC = () => {
    // State to manage the currently displayed view.
    const [activeView, setActiveView] = useState<View>('Dashboard');

    // This function returns the component that corresponds to the active view.
    const renderActiveView = () => {
        switch (activeView) {
            case 'Dashboard':
                return <Dashboard />;
            case 'AddBulkTransactions':
                return <AddBulkTransactions />;
            case 'ViewTransactions':
                return <ViewTransactions />;
            case 'SpendingInsights':
                return <SpendingInsights />;
            case 'MonthlyBalanceChecker':
                return <MonthlyBalanceChecker />;
            case 'AddReceipt':
                return <AddReceipt />;
            default:
                return <Dashboard />;
        }
    };

    return (
        <div className="flex h-screen bg-white font-sans">
            <style>{`
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
                body { font-family: 'Inter', sans-serif; }
                .animate-fade-in { animation: fadeIn 0.5s ease-in-out; }
                @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
            `}</style>
            <Sidebar activeView={activeView} setActiveView={setActiveView} />
            <main className="flex-1 p-6 sm:p-8 md:p-10 overflow-y-auto">
                {renderActiveView()}
            </main>
        </div>
    );
};

export default App;
