import React, { useState, useEffect } from 'react';
import { LayoutDashboard, PlusSquare, List, BarChart2, Calendar, Receipt, Brain } from 'lucide-react';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, PointElement, LineElement, Title, BarElement } from 'chart.js';
import { Pie, Line, Bar } from 'react-chartjs-2';
import { apiService } from './services/api';
import type { TransactionDto, MonthlyBalanceResponseDto } from './services/api';

// Register Chart.js components
ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, PointElement, LineElement, Title, BarElement);

// --- Type Definitions for TypeScript ---
// This defines the possible views our application can have.
type View =
  | 'Dashboard'
  | 'AddBulkTransactions'
  | 'ViewTransactions'
  | 'SpendingInsights'
  | 'MonthlyBalanceChecker'
  | 'AddReceipt';

// --- Welcome Header Component ---
const WelcomeHeader = () => {
    const [currentTime, setCurrentTime] = useState(new Date());

    useEffect(() => {
        const timer = setInterval(() => {
            setCurrentTime(new Date());
        }, 1000);

        return () => clearInterval(timer);
    }, []);

    const getGreeting = () => {
        const hour = currentTime.getHours();
        if (hour < 12) return 'Good Morning';
        if (hour < 17) return 'Good Afternoon';
        return 'Good Evening';
    };

    const formatDate = (date: Date) => {
        return date.toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    };

    const formatTime = (date: Date) => {
        return date.toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        });
    };

    return (
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-8 rounded-xl shadow-lg mb-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-4xl font-bold mb-2">{getGreeting()}!</h1>
                    <p className="text-xl opacity-90">Welcome to your Home Finance Dashboard</p>
                </div>
                <div className="text-right">
                    <p className="text-2xl font-semibold">{formatDate(currentTime)}</p>
                    <p className="text-xl opacity-90">{formatTime(currentTime)}</p>
                </div>
            </div>
        </div>
    );
};

// --- Athena Summary Component ---
const AthenaSummary = () => {
    return (
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm mb-8">
            <div className="flex items-center mb-4">
                <Brain className="w-6 h-6 text-purple-600 mr-3" />
                <h2 className="text-2xl font-bold text-gray-900">Athena's Insights</h2>
            </div>
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg p-6">
                <p className="text-gray-700 text-lg leading-relaxed">
                    <span className="font-semibold text-purple-700">Athena Analysis:</span> Based on your recent transactions, 
                    I've noticed some interesting patterns in your spending habits. Your grocery expenses have increased by 15% 
                    compared to last month, while entertainment spending has decreased. You're doing well with your budget 
                    allocation for utilities and transportation. Consider reviewing your dining out expenses as they're 
                    trending upward.
                </p>
                <div className="mt-4 text-sm text-gray-600">
                    <p>• Analysis based on transactions from the past 30 days</p>
                    <p>• Generated by local AI assistant Athena</p>
                </div>
            </div>
        </div>
    );
};

// --- Pie Chart Component ---
const PieChartCard = ({ title, data, colors }: { title: string; data: any; colors: string[] }) => {
    const chartData = {
        labels: data.labels,
        datasets: [
            {
                data: data.values,
                backgroundColor: colors,
                borderColor: colors.map(color => color + '80'),
                borderWidth: 2,
            },
        ],
    };

    const options = {
        responsive: true,
        plugins: {
            legend: {
                position: 'bottom' as const,
                labels: {
                    padding: 20,
                    usePointStyle: true,
                },
            },
            tooltip: {
                callbacks: {
                    label: function(context: any) {
                        const label = context.label || '';
                        const value = context.parsed;
                        const total = context.dataset.data.reduce((a: number, b: number) => a + b, 0);
                        const percentage = ((value / total) * 100).toFixed(1);
                        return `${label}: $${value.toLocaleString()} (${percentage}%)`;
                    }
                }
            }
        },
    };

    return (
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">{title}</h3>
            <div className="h-64">
                <Pie data={chartData} options={options} />
            </div>
        </div>
    );
};

// --- Dashboard Component ---
const Dashboard = () => {
    const [categoryData, setCategoryData] = useState<{ labels: string[]; values: number[] }>({ labels: [], values: [] });
    const [merchantData, setMerchantData] = useState<{ labels: string[]; values: number[] }>({ labels: [], values: [] });
    const [monthlyData, setMonthlyData] = useState<{ labels: string[]; values: number[] }>({ labels: [], values: [] });
    const [isLoading, setIsLoading] = useState(true);

    const colors = [
        '#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#06B6D4',
        '#84CC16', '#F97316', '#EC4899', '#6366F1', '#14B8A6', '#F43F5E'
    ];

    useEffect(() => {
        const loadDashboardData = async () => {
            try {
                // Get current date and 3 months ago
                const now = new Date();
                const threeMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 3, 1);
                const startDate = threeMonthsAgo.toISOString().split('T')[0];
                const endDate = now.toISOString().split('T')[0];

                // Load category data
                const categoryResponse = await apiService.getExpensesByCategory(startDate, endDate);
                if (categoryResponse) {
                    setCategoryData({
                        labels: Object.keys(categoryResponse.totals),
                        values: Object.values(categoryResponse.totals).map(val => Number(val))
                    });
                }

                // Load merchant data
                const merchantResponse = await apiService.getExpensesByEntity(startDate, endDate);
                if (merchantResponse) {
                    setMerchantData({
                        labels: Object.keys(merchantResponse.totals),
                        values: Object.values(merchantResponse.totals).map(val => Number(val))
                    });
                }

                // Load monthly data
                const startMonth = threeMonthsAgo.toISOString().slice(0, 7); // YYYY-MM format
                const endMonth = now.toISOString().slice(0, 7);
                const monthlyResponse = await apiService.getExpensesByMonth(startMonth, endMonth);
                if (monthlyResponse) {
                    setMonthlyData({
                        labels: Object.keys(monthlyResponse.totals).map(month => {
                            const [year, monthNum] = month.split('-');
                            const date = new Date(parseInt(year), parseInt(monthNum) - 1);
                            return date.toLocaleDateString('en-US', { month: 'long' });
                        }),
                        values: Object.values(monthlyResponse.totals).map(val => Number(val))
                    });
                }
            } catch (error) {
                console.error('Error loading dashboard data:', error);
            } finally {
                setIsLoading(false);
            }
        };

        loadDashboardData();
    }, []);

    if (isLoading) {
        return (
            <div className="max-w-7xl mx-auto animate-fade-in">
                <WelcomeHeader />
                <div className="flex items-center justify-center h-64">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
                    <span className="ml-3 text-gray-600">Loading dashboard data...</span>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-7xl mx-auto animate-fade-in">
            <WelcomeHeader />
            <AthenaSummary />
            
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <PieChartCard 
                    title="Spending by Category (Past 3 Months)" 
                    data={categoryData} 
                    colors={colors.slice(0, 6)} 
                />
                <PieChartCard 
                    title="Spending by Merchant (Past 3 Months)" 
                    data={merchantData} 
                    colors={colors.slice(6, 12)} 
                />
                <BarChartCard 
                    title="Spending by Month (Past 3 Months)" 
                    data={monthlyData} 
                    colors={colors.slice(0, 3)} 
                />
            </div>
        </div>
    );
};

const AddBulkTransactions = () => {
    const [selectedBank, setSelectedBank] = useState<'Amex' | 'CIBC' | null>(null);
    const [selectedFile, setSelectedFile] = useState<File | null>(null);

    // Console logging utility for component
    const log = {
        info: (message: string, data?: any) => {
            console.log(`[AddBulkTransactions] ${message}`, data || '');
        },
        error: (message: string, error?: any) => {
            console.error(`[AddBulkTransactions ERROR] ${message}`, error || '');
        },
        debug: (message: string, data?: any) => {
            console.debug(`[AddBulkTransactions DEBUG] ${message}`, data || '');
        }
    };

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (file) {
            log.info(`File selected: ${file.name} (${file.size} bytes, type: ${file.type})`);
            log.debug('File details:', {
                name: file.name,
                size: file.size,
                type: file.type,
                lastModified: new Date(file.lastModified).toISOString()
            });
            setSelectedFile(file);
        } else {
            log.info('No file selected');
        }
    };

    const handleAddTransactions = async () => {
        log.info('Starting file upload process');
        log.debug('Current state:', { selectedBank, selectedFile: selectedFile?.name });
        
        if (!selectedBank || !selectedFile) {
            log.error('Missing required data for upload', { selectedBank, hasFile: !!selectedFile });
            alert('Please select a bank and upload a file');
            return;
        }
        
        try {
            const sourceType = selectedBank === 'Amex' ? 'amex' : 'cibc';
            log.info(`Preparing to upload file with source type: ${sourceType}`);
            
            const result = await apiService.uploadTransactionFile(selectedFile, sourceType);
            log.info('File upload successful:', result);
            alert(`Successfully uploaded ${selectedFile.name} for ${selectedBank} transactions`);
            
            // Reset form
            log.info('Resetting form after successful upload');
            setSelectedBank(null);
            setSelectedFile(null);
        } catch (error) {
            log.error('File upload failed:', error);
            console.error('Error uploading file:', error);
            alert('Failed to upload file. Please try again.');
        }
    };

    return (
        <div className="animate-fade-in max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Upload Transactions File</h2>
            
            {/* Bank Selection */}
            <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">Select Bank</label>
                <div className="flex space-x-4">
                    <button
                        onClick={() => {
                            log.info('Bank selected: Amex');
                            setSelectedBank('Amex');
                        }}
                        className={`px-6 py-3 rounded-lg font-medium transition-colors duration-200 ${
                            selectedBank === 'Amex'
                                ? 'bg-blue-600 text-white shadow-md'
                                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                        }`}
                    >
                        Amex
                    </button>
                    <button
                        onClick={() => {
                            log.info('Bank selected: CIBC');
                            setSelectedBank('CIBC');
                        }}
                        className={`px-6 py-3 rounded-lg font-medium transition-colors duration-200 ${
                            selectedBank === 'CIBC'
                                ? 'bg-blue-600 text-white shadow-md'
                                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                        }`}
                    >
                        CIBC
                    </button>
                </div>
            </div>

            {/* File Upload */}
            <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">Upload File</label>
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-gray-400 transition-colors duration-200">
                    <input
                        type="file"
                        accept=".csv,.xlsx,.xls"
                        onChange={handleFileChange}
                        className="hidden"
                        id="file-upload"
                    />
                    <label htmlFor="file-upload" className="cursor-pointer">
                        <div className="space-y-2">
                            <div className="text-gray-400">
                                <svg className="mx-auto h-12 w-12" stroke="currentColor" fill="none" viewBox="0 0 48 48">
                                    <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                            </div>
                            <div className="text-gray-600">
                                <span className="font-medium">Click to upload</span> or drag and drop
                            </div>
                            <div className="text-sm text-gray-500">CSV, XLSX, or XLS files</div>
                        </div>
                    </label>
                </div>
                {selectedFile && (
                    <div className="mt-3 p-3 bg-green-50 border border-green-200 rounded-lg">
                        <div className="flex items-center">
                            <svg className="w-5 h-5 text-green-500 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                            </svg>
                            <span className="text-green-700 font-medium">{selectedFile.name}</span>
                        </div>
                    </div>
                )}
            </div>

            {/* Add Transactions Button */}
            <div className="flex justify-center">
                <button
                    onClick={handleAddTransactions}
                    disabled={!selectedBank || !selectedFile}
                    className={`px-8 py-3 rounded-lg font-medium transition-colors duration-200 ${
                        selectedBank && selectedFile
                            ? 'bg-green-600 text-white hover:bg-green-700 shadow-md'
                            : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    }`}
                >
                    Add Transactions
                </button>
            </div>
        </div>
    );
};

const ViewTransactions = () => {
    const [startDate, setStartDate] = useState<string>('');
    const [endDate, setEndDate] = useState<string>('');
    const [transactions, setTransactions] = useState<TransactionDto[]>([]);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string>('');

    const handleFilter = async () => {
        if (!startDate || !endDate) {
            alert('Please select both start and end dates');
            return;
        }

        setIsLoading(true);
        setError('');
        
        try {
            const data = await apiService.getTransactionsByDateRange(startDate, endDate);
            setTransactions(data);
        } catch (err) {
            console.error('Error fetching transactions:', err);
            setError('Failed to fetch transactions. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('en-CA', {
            style: 'currency',
            currency: 'CAD'
        }).format(Math.abs(amount));
    };

    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleDateString('en-CA', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        });
    };

    return (
        <div className="animate-fade-in max-w-7xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">View Transactions</h2>
            
            {/* Date Filter Section */}
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm mb-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Filter by Date Range</h3>
                <div className="flex flex-col sm:flex-row gap-4 items-end">
                    <div className="flex-1">
                        <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                        <input
                            type="date"
                            value={startDate}
                            onChange={(e) => setStartDate(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>
                    <div className="flex-1">
                        <label className="block text-sm font-medium text-gray-700 mb-2">End Date</label>
                        <input
                            type="date"
                            value={endDate}
                            onChange={(e) => setEndDate(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>
                    <button
                        onClick={handleFilter}
                        disabled={!startDate || !endDate || isLoading}
                        className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                            startDate && endDate && !isLoading
                                ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md'
                                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                        }`}
                    >
                        {isLoading ? 'Loading...' : 'Filter'}
                    </button>
                </div>
            </div>

            {/* Error Display */}
            {error && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
                    <div className="flex items-center">
                        <svg className="w-5 h-5 text-red-500 mr-2" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                        </svg>
                        <span className="text-red-700 font-medium">{error}</span>
                    </div>
                </div>
            )}

            {/* Transactions Table */}
            <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-200">
                    <h3 className="text-lg font-semibold text-gray-900">
                        Transactions {transactions.length > 0 && `(${transactions.length} found)`}
                    </h3>
                </div>
                
                {transactions.length === 0 && !isLoading ? (
                    <div className="p-8 text-center text-gray-500">
                        <svg className="mx-auto h-12 w-12 text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        <p className="text-lg font-medium">No transactions found</p>
                        <p className="text-sm">Select a date range and click Filter to view transactions</p>
                    </div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-gray-200">
                            <thead className="bg-gray-50">
                                <tr>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Date
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Type
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Amount
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Account
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Category
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-200">
                                {isLoading ? (
                                    <tr>
                                        <td colSpan={5} className="px-6 py-4 text-center">
                                            <div className="flex items-center justify-center">
                                                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-600"></div>
                                                <span className="ml-2 text-gray-600">Loading transactions...</span>
                                            </div>
                                        </td>
                                    </tr>
                                ) : (
                                    transactions.map((transaction, index) => (
                                        <tr key={index} className="hover:bg-gray-50">
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                {formatDate(transaction.date)}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap">
                                                <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                                    transaction.transactionType === 'INCOME' 
                                                        ? 'bg-green-100 text-green-800' 
                                                        : 'bg-red-100 text-red-800'
                                                }`}>
                                                    {transaction.transactionType}
                                                </span>
                                            </td>
                                            <td className={`px-6 py-4 whitespace-nowrap text-sm font-medium ${
                                                transaction.amount >= 0 ? 'text-green-600' : 'text-red-600'
                                            }`}>
                                                {transaction.amount >= 0 ? '+' : '-'}{formatCurrency(transaction.amount)}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                {transaction.account}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                {transaction.category}
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
};

// Bar Chart Component for monthly spending
const BarChartCard = ({ title, data, colors }: { title: string; data: any; colors: string[] }) => {
    const chartData = {
        labels: data.labels,
        datasets: [
            {
                label: 'Spending',
                data: data.values,
                backgroundColor: colors,
                borderColor: colors.map(color => color + '80'),
                borderWidth: 1,
            },
        ],
    };

    const options = {
        responsive: true,
        plugins: {
            legend: {
                display: false,
            },
            tooltip: {
                callbacks: {
                    label: function(context: any) {
                        return `$${context.parsed.y.toLocaleString()}`;
                    }
                }
            }
        },
        scales: {
            y: {
                beginAtZero: true,
                ticks: {
                    callback: function(value: any) {
                        return '$' + value.toLocaleString();
                    }
                }
            }
        }
    };

    return (
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">{title}</h3>
            <div className="h-64">
                <Bar data={chartData} options={options} />
            </div>
        </div>
    );
};

const SpendingInsights = () => {
    const [selectedOption, setSelectedOption] = useState<string>('');
    const [athenaQuery, setAthenaQuery] = useState<string>('');
    const [athenaResponse, setAthenaResponse] = useState<string>('');
    const [isAthenaLoading, setIsAthenaLoading] = useState<boolean>(false);
    const [startDate, setStartDate] = useState<string>('');
    const [endDate, setEndDate] = useState<string>('');
    const [startMonth, setStartMonth] = useState<string>('');
    const [endMonth, setEndMonth] = useState<string>('');
    const [chartData, setChartData] = useState<any>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);

    const colors = [
        '#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#06B6D4',
        '#84CC16', '#F97316', '#EC4899', '#6366F1', '#14B8A6', '#F43F5E'
    ];

    // Sample data for different chart types
    // const sampleCategoryData = {
    //     labels: ['Groceries', 'Entertainment', 'Transportation', 'Utilities', 'Dining', 'Shopping'],
    //     values: [1200, 800, 600, 400, 350, 300]
    // };

    // const sampleMerchantData = {
    //     labels: ['Walmart', 'Netflix', 'Shell', 'Hydro One', 'Restaurant A', 'Amazon'],
    //     values: [800, 15, 200, 150, 300, 250]
    // };

    // const sampleMonthlyData = {
    //     labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    //     values: [2800, 3200, 2650, 3100, 2900, 3400]
    // };

    const handleAthenaSubmit = () => {
        if (!athenaQuery.trim()) {
            alert('Please enter a question for Athena');
            return;
        }

        setIsAthenaLoading(true);
        
        // Simulate AI response delay
        setTimeout(() => {
            setAthenaResponse(`Athena's Analysis: Based on your question "${athenaQuery}", I can see that your spending patterns show interesting trends. Your grocery expenses have increased by 15% compared to last month, while entertainment spending has decreased. You're doing well with your budget allocation for utilities and transportation. Consider reviewing your dining out expenses as they're trending upward.`);
            setIsAthenaLoading(false);
        }, 2000);
    };

    const handleDateRangeSubmit = async () => {
        if (!startDate || !endDate) {
            alert('Please select both start and end dates');
            return;
        }

        setIsLoading(true);
        
        try {
            let data;
            if (selectedOption === 'category') {
                data = await apiService.getExpensesByCategory(startDate, endDate);
            } else if (selectedOption === 'merchant') {
                data = await apiService.getExpensesByEntity(startDate, endDate);
            }
            
            if (data) {
                const chartData = {
                    labels: Object.keys(data.totals),
                    values: Object.values(data.totals).map(val => Number(val))
                };
                setChartData(chartData);
            }
        } catch (error) {
            console.error('Error fetching data:', error);
            alert('Failed to fetch data. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleMonthlySubmit = async () => {
        if (!startMonth || !endMonth) {
            alert('Please select both start and end months');
            return;
        }

        setIsLoading(true);
        
        try {
            const data = await apiService.getExpensesByMonth(startMonth, endMonth);
            
            if (data) {
                const chartData = {
                    labels: Object.keys(data.totals).map(month => {
                        // Convert "2025-04" to "Apr 2025"
                        const [year, monthNum] = month.split('-');
                        const date = new Date(parseInt(year), parseInt(monthNum) - 1);
                        return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
                    }),
                    values: Object.values(data.totals).map(val => Number(val))
                };
                setChartData(chartData);
            }
        } catch (error) {
            console.error('Error fetching monthly data:', error);
            alert('Failed to fetch monthly data. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    const renderOptionContent = () => {
        switch (selectedOption) {
            case 'athena':
                return (
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Ask Athena's Analysis</h3>
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">Your Question</label>
                                <textarea
                                    value={athenaQuery}
                                    onChange={(e) => setAthenaQuery(e.target.value)}
                                    placeholder="Ask Athena about your spending patterns, budget advice, or financial insights..."
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500 h-24 resize-none"
                                />
                            </div>
                            <button
                                onClick={handleAthenaSubmit}
                                disabled={!athenaQuery.trim() || isAthenaLoading}
                                className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                                    athenaQuery.trim() && !isAthenaLoading
                                        ? 'bg-purple-600 text-white hover:bg-purple-700 shadow-md'
                                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                }`}
                            >
                                {isAthenaLoading ? 'Analyzing...' : 'Submit to Athena'}
                            </button>
                            {athenaResponse && (
                                <div className="mt-6 p-4 bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg">
                                    <p className="text-gray-700 leading-relaxed">{athenaResponse}</p>
                                </div>
                            )}
                        </div>
                    </div>
                );

            case 'category':
                return (
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Spending by Category</h3>
                        <div className="space-y-4">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                                    <input
                                        type="date"
                                        value={startDate}
                                        onChange={(e) => setStartDate(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">End Date</label>
                                    <input
                                        type="date"
                                        value={endDate}
                                        onChange={(e) => setEndDate(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                            </div>
                            <button
                                onClick={handleDateRangeSubmit}
                                disabled={!startDate || !endDate || isLoading}
                                className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                                    startDate && endDate && !isLoading
                                        ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md'
                                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                }`}
                            >
                                {isLoading ? 'Loading...' : 'Submit'}
                            </button>
                            {chartData && (
                                <div className="mt-6">
                                    <PieChartCard 
                                        title="Spending by Category" 
                                        data={chartData} 
                                        colors={colors.slice(0, 6)} 
                                    />
                                </div>
                            )}
                        </div>
                    </div>
                );

            case 'merchant':
                return (
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Top Merchants</h3>
                        <div className="space-y-4">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                                    <input
                                        type="date"
                                        value={startDate}
                                        onChange={(e) => setStartDate(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">End Date</label>
                                    <input
                                        type="date"
                                        value={endDate}
                                        onChange={(e) => setEndDate(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                            </div>
                            <button
                                onClick={handleDateRangeSubmit}
                                disabled={!startDate || !endDate || isLoading}
                                className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                                    startDate && endDate && !isLoading
                                        ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md'
                                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                }`}
                            >
                                {isLoading ? 'Loading...' : 'Submit'}
                            </button>
                            {chartData && (
                                <div className="mt-6">
                                    <PieChartCard 
                                        title="Top Merchants" 
                                        data={chartData} 
                                        colors={colors.slice(6, 12)} 
                                    />
                                </div>
                            )}
                        </div>
                    </div>
                );

            case 'monthly':
                return (
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Spending by Month</h3>
                        <div className="space-y-4">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Start Month</label>
                                    <input
                                        type="month"
                                        value={startMonth}
                                        onChange={(e) => setStartMonth(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">End Month</label>
                                    <input
                                        type="month"
                                        value={endMonth}
                                        onChange={(e) => setEndMonth(e.target.value)}
                                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                </div>
                            </div>
                            <button
                                onClick={handleMonthlySubmit}
                                disabled={!startMonth || !endMonth || isLoading}
                                className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                                    startMonth && endMonth && !isLoading
                                        ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md'
                                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                }`}
                            >
                                {isLoading ? 'Loading...' : 'Submit'}
                            </button>
                            {chartData && (
                                <div className="mt-6">
                                    <BarChartCard 
                                        title="Monthly Spending" 
                                        data={chartData} 
                                        colors={colors.slice(0, 6)} 
                                    />
                                </div>
                            )}
                        </div>
                    </div>
                );

            default:
                return (
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <div className="text-center text-gray-500">
                            <svg className="mx-auto h-12 w-12 text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                            </svg>
                            <p className="text-lg font-medium">Select an option to view insights</p>
                            <p className="text-sm">Choose from the options above to analyze your spending patterns</p>
                        </div>
                    </div>
                );
        }
    };

    return (
        <div className="animate-fade-in max-w-7xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Spending Insights</h2>
            
            {/* Option Selection */}
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm mb-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Choose Analysis Type</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    <button
                        onClick={() => setSelectedOption('athena')}
                        className={`p-4 rounded-lg border-2 transition-colors duration-200 ${
                            selectedOption === 'athena'
                                ? 'border-purple-500 bg-purple-50 text-purple-700'
                                : 'border-gray-200 hover:border-gray-300 text-gray-700'
                        }`}
                    >
                        <div className="text-center">
                            <Brain className="w-8 h-8 mx-auto mb-2" />
                            <span className="font-medium">Ask Athena's Analysis</span>
                        </div>
                    </button>
                    <button
                        onClick={() => setSelectedOption('category')}
                        className={`p-4 rounded-lg border-2 transition-colors duration-200 ${
                            selectedOption === 'category'
                                ? 'border-blue-500 bg-blue-50 text-blue-700'
                                : 'border-gray-200 hover:border-gray-300 text-gray-700'
                        }`}
                    >
                        <div className="text-center">
                            <BarChart2 className="w-8 h-8 mx-auto mb-2" />
                            <span className="font-medium">Spending by Category</span>
                        </div>
                    </button>
                    <button
                        onClick={() => setSelectedOption('merchant')}
                        className={`p-4 rounded-lg border-2 transition-colors duration-200 ${
                            selectedOption === 'merchant'
                                ? 'border-green-500 bg-green-50 text-green-700'
                                : 'border-gray-200 hover:border-gray-300 text-gray-700'
                        }`}
                    >
                        <div className="text-center">
                            <BarChart2 className="w-8 h-8 mx-auto mb-2" />
                            <span className="font-medium">Top Merchants</span>
                        </div>
                    </button>
                    <button
                        onClick={() => setSelectedOption('monthly')}
                        className={`p-4 rounded-lg border-2 transition-colors duration-200 ${
                            selectedOption === 'monthly'
                                ? 'border-orange-500 bg-orange-50 text-orange-700'
                                : 'border-gray-200 hover:border-gray-300 text-gray-700'
                        }`}
                    >
                        <div className="text-center">
                            <Calendar className="w-8 h-8 mx-auto mb-2" />
                            <span className="font-medium">Spending by Month</span>
                        </div>
                    </button>
                </div>
            </div>

            {/* Content Area */}
            {renderOptionContent()}
        </div>
    );
};

const MonthlyBalanceChecker = () => {
    const [selectedMonth, setSelectedMonth] = useState<string>('');
    const [selectedYear, setSelectedYear] = useState<string>('');
    const [balanceData, setBalanceData] = useState<MonthlyBalanceResponseDto | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);

    // Generate month options
    const months = [
        { value: '01', label: 'January' },
        { value: '02', label: 'February' },
        { value: '03', label: 'March' },
        { value: '04', label: 'April' },
        { value: '05', label: 'May' },
        { value: '06', label: 'June' },
        { value: '07', label: 'July' },
        { value: '08', label: 'August' },
        { value: '09', label: 'September' },
        { value: '10', label: 'October' },
        { value: '11', label: 'November' },
        { value: '12', label: 'December' }
    ];

    // Generate year options (current year and 5 years back)
    const currentYear = new Date().getFullYear();
    const years = Array.from({ length: 6 }, (_, i) => currentYear - i);

    const handleCheckBalance = async () => {
        if (!selectedMonth || !selectedYear) {
            alert('Please select both month and year');
            return;
        }

        setIsLoading(true);
        
        try {
            const data = await apiService.getMonthlyBalance(selectedMonth, selectedYear);
            setBalanceData(data);
        } catch (error) {
            console.error('Error fetching monthly balance:', error);
            alert('Failed to fetch monthly balance. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('en-CA', {
            style: 'currency',
            currency: 'CAD'
        }).format(amount);
    };

    const getMonthName = (monthValue: string) => {
        const month = months.find(m => m.value === monthValue);
        return month ? month.label : '';
    };

    return (
        <div className="animate-fade-in max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Monthly Balance Checker</h2>
            
            {/* Selection Controls */}
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm mb-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Select Month and Year</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 items-end">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Month</label>
                        <select
                            value={selectedMonth}
                            onChange={(e) => setSelectedMonth(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        >
                            <option value="">Select Month</option>
                            {months.map((month) => (
                                <option key={month.value} value={month.value}>
                                    {month.label}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Year</label>
                        <select
                            value={selectedYear}
                            onChange={(e) => setSelectedYear(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        >
                            <option value="">Select Year</option>
                            {years.map((year) => (
                                <option key={year} value={year}>
                                    {year}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>
                <div className="mt-4">
                    <button
                        onClick={handleCheckBalance}
                        disabled={!selectedMonth || !selectedYear || isLoading}
                        className={`px-6 py-2 rounded-lg font-medium transition-colors duration-200 ${
                            selectedMonth && selectedYear && !isLoading
                                ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-md'
                                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                        }`}
                    >
                        {isLoading ? 'Checking...' : 'Check Balance'}
                    </button>
                </div>
            </div>

            {/* Results Display */}
            {balanceData && (
                <div className="space-y-6">
                    {/* Summary Section */}
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Monthly Balance Summary</h3>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                                <p className="text-blue-800 font-medium">
                                    Asanka's Total: {formatCurrency(balanceData.asankaTotal)}
                                </p>
                            </div>
                            <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                                <p className="text-green-800 font-medium">
                                    Divya's Total: {formatCurrency(balanceData.divyaTotal)}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* Balance Result */}
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4">Balance Result</h3>
                        {balanceData.whoOwes ? (
                            <div className="p-4 bg-orange-50 border border-orange-200 rounded-lg">
                                <p className="text-orange-800 font-medium">
                                    {balanceData.whoOwes} owes {formatCurrency(balanceData.amount)} to the other person
                                </p>
                            </div>
                        ) : (
                            <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                                <p className="text-green-800 font-medium">
                                    Perfect balance! Both parties have paid equally.
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            )}

            {/* Empty State */}
            {!balanceData && !isLoading && (
                <div className="bg-white border border-gray-200 rounded-xl p-8 shadow-sm text-center">
                    <svg className="mx-auto h-12 w-12 text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                    </svg>
                    <p className="text-lg font-medium text-gray-900 mb-2">No Balance Data</p>
                    <p className="text-gray-600">Select a month and year, then click "Check Balance" to view the monthly balance information.</p>
                </div>
            )}

            {/* Loading State */}
            {isLoading && (
                <div className="bg-white border border-gray-200 rounded-xl p-8 shadow-sm text-center">
                    <div className="flex items-center justify-center">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                        <span className="ml-3 text-gray-600">Checking balance for {getMonthName(selectedMonth)} {selectedYear}...</span>
                    </div>
                </div>
            )}
        </div>
    );
};

const AddReceipt = () => (
    <div className="animate-fade-in">
        <h2 className="text-3xl font-bold text-gray-900">Add Receipt</h2>
        <p className="mt-2 text-gray-600">Upload a receipt to automatically create a transaction.</p>
    </div>
);

// --- Sidebar Navigation Component ---
interface SidebarProps {
    activeView: View;
    setActiveView: (view: View) => void;
}

const Sidebar: React.FC<SidebarProps> = ({ activeView, setActiveView }) => {
    const menuItems: { id: number; name: View; icon: React.ElementType }[] = [
        { id: 1, name: 'Dashboard', icon: LayoutDashboard },
        { id: 2, name: 'AddBulkTransactions', icon: PlusSquare },
        { id: 3, name: 'ViewTransactions', icon: List },
        { id: 4, name: 'SpendingInsights', icon: BarChart2 },
        { id: 5, name: 'MonthlyBalanceChecker', icon: Calendar },
        { id: 6, name: 'AddReceipt', icon: Receipt },
    ];

    // Function to format the view name for display
    const formatViewName = (name: View) => name.replace(/([A-Z])/g, ' $1').trim();

    return (
        <aside className="w-64 flex-shrink-0 bg-gray-100/95 border-r border-gray-200 flex flex-col transition-all duration-300">
            <div className="h-16 flex items-center px-6 border-b border-gray-200">
                <h1 className="text-xl font-bold text-gray-900">Home Finance</h1>
            </div>
            <nav className="flex-1 px-4 py-4 space-y-1">
                {menuItems.map((item) => {
                    const isActive = activeView === item.name;
                    return (
                        <a
                            key={item.id}
                            href="#"
                            onClick={(e) => {
                                e.preventDefault();
                                setActiveView(item.name);
                            }}
                            className={`flex items-center px-4 py-2.5 text-sm font-medium rounded-lg transition-colors duration-200 ${
                                isActive
                                    ? 'bg-gray-200 text-gray-900 font-semibold'
                                    : 'text-gray-600 hover:bg-gray-200/70 hover:text-gray-800'
                            }`}
                        >
                            <item.icon className="w-5 h-5 mr-3" />
                            {formatViewName(item.name)}
                        </a>
                    );
                })}
            </nav>
        </aside>
    );
};


// --- Main App Component ---
const App: React.FC = () => {
    // State to manage the currently displayed view.
    const [activeView, setActiveView] = useState<View>('Dashboard');

    // This function returns the component that corresponds to the active view.
    const renderActiveView = () => {
        switch (activeView) {
            case 'Dashboard':
                return <Dashboard />;
            case 'AddBulkTransactions':
                return <AddBulkTransactions />;
            case 'ViewTransactions':
                return <ViewTransactions />;
            case 'SpendingInsights':
                return <SpendingInsights />;
            case 'MonthlyBalanceChecker':
                return <MonthlyBalanceChecker />;
            case 'AddReceipt':
                return <AddReceipt />;
            default:
                return <Dashboard />;
        }
    };

    return (
        <div className="flex h-screen bg-white font-sans">
            <style>{`
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
                body { font-family: 'Inter', sans-serif; }
                .animate-fade-in { animation: fadeIn 0.5s ease-in-out; }
                @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
            `}</style>
            <Sidebar activeView={activeView} setActiveView={setActiveView} />
            <main className="flex-1 p-6 sm:p-8 md:p-10 overflow-y-auto">
                {renderActiveView()}
            </main>
        </div>
    );
};

export default App;
