spring.application.name=homefinance
spring.data.mongodb.database=finance-api-db
spring.data.mongodb.uri=mongodb+srv://asankanz:nLGPApJ5QLMKLTji@cluster0.kqfad.mongodb.net/
server.port=8585

# MySQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway configs
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=1
# Disable auto hibernate auto creating tables
spring.jpa.hibernate.ddl-auto=none

# Hibernate JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

# Enable logging for Spring Boot
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.ca.homefinance=DEBUG

# Athena configuration
# Local AI (e.g., Ollama)
athena.local.url=http://host.docker.internal:11434/api/generate

#athena.local.model=deepseek-r1:14b
athena.local.model=gpt-oss:20b
# External AI (OpenAI default)
athena.external.provider=openai
athena.external.model=gpt-4o-mini
athena.external.openai.baseUrl=https://api.openai.com/v1/chat/completions
# Set in environment or a secure config store
athena.external.openai.apiKey=